server:
  port: 9000

spring:
  application:
    name: Api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: trip-backend
          uri: http://localhost:8080
          predicates:
           - Path=/cliente,/viaje
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/